### ISSUE TITLE
Resource not found when trying to pause a transferred call

### ISSUE THREAD

**Issue by gturn27** [aws-samples/ac-recordingapis#1]
When a call is transferred from agent A to agent B, agent B is not able to pause the recording.  Pressing the pause button returns an error of:   'Failed to : PAUSE error : Resource not found'.  Pressing the Resume, Start and Stop buttons return the same error.  It seems to be a problem with the setRecordingStatus() function, but I'm having a hard time finding it.

**Comment by gturn27** [comment]
This ended up being a problem with the initialContactId being set to c.contactID.  Setting it to c.getInitialContactID() resolved the problem.

**Comment by ramprasadsv** [comment]
@gturn27 you are spot on, for the transfers you need to use the initialContactId.
